name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Zip integration
        run: |
          cd custom_components/lds
          zip -r ../../ha-lds.zip . -x "*.pyc" "*/__pycache__/*"

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./ha-lds.zip
          asset_name: ha-lds.zip
          asset_content_type: application/zip
